#!/usr/bin/env python3
"""
analyzer.py — Slicer Lab, CLI companion.

Three real, working tools, same logic as engine.js (the in-browser version
on Index.html):
  1. G-code Analyzer — reads the slicer's own summary comments out of a
     .gcode file (print time, filament used, cost, material, temperatures),
     plus a couple of computed stats (layer count, line count).
  2. Material Settings Advisor — prints the same fixed reference table as
     database.sql / engine.js's MATERIAL_PROFILES.
  3. Filament Cost Calculator — weight (g) + price/kg -> cost.

Usage:
    python analyzer.py "../Freelance/33m,PETG,cabletiebelttensioner.gcode"
    python analyzer.py --materials
    python analyzer.py --cost 56.5 4500
    python analyzer.py --cost 56.5 4500 --qty 3
"""

import argparse
import re
import sqlite3
import sys
from pathlib import Path

for _stream in (sys.stdout, sys.stderr):
    if hasattr(_stream, "reconfigure"):
        _stream.reconfigure(encoding="utf-8")

HERE = Path(__file__).resolve().parent
DEFAULT_DB = HERE / "slicer.db"
SCHEMA_SQL = HERE / "database.sql"

FIELD_PATTERNS = {
    "generated_by": re.compile(r";\s*generated by\s+(.+)$", re.IGNORECASE | re.MULTILINE),
    "print_time": re.compile(r";\s*estimated printing time \(normal mode\)\s*=\s*(.+)$", re.IGNORECASE | re.MULTILINE),
    "filament_mm": re.compile(r";\s*filament used \[mm\]\s*=\s*([\d.]+)", re.IGNORECASE),
    "filament_cm3": re.compile(r";\s*filament used \[cm3\]\s*=\s*([\d.]+)", re.IGNORECASE),
    "filament_g": re.compile(r";\s*filament used \[g\]\s*=\s*([\d.]+)", re.IGNORECASE),
    "filament_cost": re.compile(r";\s*filament cost\s*=\s*([\d.]+)", re.IGNORECASE),
    "material": re.compile(r";\s*filament_type\s*=\s*(\S+)", re.IGNORECASE),
    "nozzle_temp": re.compile(r";\s*temperature\s*=\s*(\d+)", re.IGNORECASE),
    "bed_temp": re.compile(r";\s*bed_temperature\s*=\s*(\d+)", re.IGNORECASE),
    "nozzle_diameter": re.compile(r";\s*nozzle_diameter\s*=\s*([\d.]+)", re.IGNORECASE),
    "layer_height": re.compile(r";\s*layer_height\s*=\s*([\d.]+)", re.IGNORECASE),
}


def ensure_database(db_path=DEFAULT_DB, schema_path=SCHEMA_SQL):
    conn = sqlite3.connect(db_path)
    with open(schema_path, encoding="utf-8") as f:
        conn.executescript(f.read())
    conn.commit()
    return conn


def parse_gcode(text):
    stats = {}
    for key, pattern in FIELD_PATTERNS.items():
        m = pattern.search(text)
        stats[key] = m.group(1).strip() if m else None
    stats["layer_changes"] = len(re.findall(r";LAYER_CHANGE", text))
    stats["line_count"] = text.count("\n") + 1
    stats["g1_moves"] = len(re.findall(r"^G1 ", text, re.MULTILINE))
    stats["found"] = any([stats["generated_by"], stats["print_time"], stats["filament_g"], stats["material"]])
    return stats


def format_report(stats, filename):
    lines = [f"G-code Analysis — {filename}", "=" * (18 + len(filename))]
    if not stats["found"]:
        lines.append("No PrusaSlicer-style summary comments found in this file.")
        lines.append("Computed stats (still real, read straight from the file):")
        lines.append(f"  Line count:              {stats['line_count']:,}")
        lines.append(f"  G1 move commands:        {stats['g1_moves']:,}")
        lines.append(f"  Layer changes:           {stats['layer_changes']:,}")
        return "\n".join(lines)

    def add(label, value, suffix=""):
        if value:
            lines.append(f"  {label:<24} {value}{suffix}")

    add("Sliced by:", stats["generated_by"])
    add("Material:", stats["material"])
    add("Estimated print time:", stats["print_time"])
    add("Filament used:", stats["filament_g"], " g")
    add("Filament length:", stats["filament_mm"], " mm")
    add("Filament volume:", stats["filament_cm3"], " cm3")
    add("Filament cost:", stats["filament_cost"], " (slicer-configured units)")
    add("Nozzle temperature:", stats["nozzle_temp"], " C")
    add("Bed temperature:", stats["bed_temp"], " C")
    add("Nozzle diameter:", stats["nozzle_diameter"], " mm")
    add("Layer height:", stats["layer_height"], " mm")
    add("Layer changes:", f"{stats['layer_changes']:,}")
    add("Line count:", f"{stats['line_count']:,}")
    add("G1 move commands:", f"{stats['g1_moves']:,}")
    return "\n".join(lines)


def print_materials(db_path=DEFAULT_DB):
    conn = ensure_database(db_path)
    rows = conn.execute(
        "SELECT material, nozzle_temp_min, nozzle_temp_max, bed_temp_min, bed_temp_max, fan_hint, speed_hint, notes "
        "FROM material_profiles ORDER BY id"
    ).fetchall()
    conn.close()
    print("Material Settings Advisor")
    print("=" * 26)
    for material, n_min, n_max, b_min, b_max, fan, speed, notes in rows:
        print(f"\n{material}")
        print(f"  Nozzle: {n_min}-{n_max} C    Bed: {b_min}-{b_max} C")
        print(f"  Fan:    {fan}")
        print(f"  Speed:  {speed}")
        print(f"  Notes:  {notes}")


def print_cost(weight_g, price_per_kg, qty):
    cost_per_part = (weight_g / 1000.0) * price_per_kg
    total = cost_per_part * qty
    print(f"Filament weight:   {weight_g} g")
    print(f"Price per kg:      {price_per_kg}")
    print(f"Cost per part:     {cost_per_part:.2f}")
    if qty != 1:
        print(f"Quantity:          {qty}")
        print(f"Total cost:        {total:.2f}")
    print("(same currency units as the price you entered)")


def print_real_jobs(db_path=DEFAULT_DB):
    conn = ensure_database(db_path)
    rows = conn.execute(
        "SELECT part_name, material, print_time, filament_g, filament_cost, nozzle_temp, bed_temp, note, filename "
        "FROM real_jobs ORDER BY id"
    ).fetchall()
    conn.close()
    print("Real jobs from this portfolio (../Freelance)")
    print("=" * 45)
    for part, material, t, g, cost, nozzle, bed, note, filename in rows:
        print(f"\n{part}  [{filename}]")
        print(f"  Material: {material}    Time: {t}    Filament: {g} g    Cost: {cost}")
        print(f"  Temps: {nozzle} C nozzle / {bed} C bed")
        if note:
            print(f"  Note: {note}")


def main():
    parser = argparse.ArgumentParser(description="Slicer Lab — G-code analyzer, material advisor, and cost calculator.")
    parser.add_argument("gcode", nargs="?", help="Path to a .gcode file to analyze.")
    parser.add_argument("--db", default=str(DEFAULT_DB), help="Path to the SQLite database.")
    parser.add_argument("--materials", action="store_true", help="Print the Material Settings Advisor table.")
    parser.add_argument("--jobs", action="store_true", help="Print the real jobs table from this portfolio.")
    parser.add_argument("--cost", nargs=2, type=float, metavar=("WEIGHT_G", "PRICE_PER_KG"), help="Filament cost calculator.")
    parser.add_argument("--qty", type=int, default=1, help="Quantity, used with --cost.")
    args = parser.parse_args()

    if args.materials:
        print_materials(args.db)
        return
    if args.jobs:
        print_real_jobs(args.db)
        return
    if args.cost:
        print_cost(args.cost[0], args.cost[1], args.qty)
        return
    if not args.gcode:
        parser.error("pass a .gcode file, or one of --materials / --jobs / --cost")

    path = Path(args.gcode)
    if not path.exists():
        sys.exit(f"error: file not found: {path}")
    text = path.read_text(encoding="utf-8", errors="replace")
    stats = parse_gcode(text)
    print(format_report(stats, path.name))


if __name__ == "__main__":
    main()
